name: PR Preview
on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
      - closed
concurrency: preview-${{ github.ref }}
permissions:
  contents: write
jobs:
  pr-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.7
        with:
          source-dir: ./build/
          token: ${{ secrets.TOKEN_GITHUB }}
            